constant RI_BASE($A470)       // $04700000 RDRAM Interface (RI) Base
constant RI_MODE($00)         // $04700000 Mode
constant RI_CONFIG($04)       // $04700004 Config
constant RI_CURRENT_LOAD($08) // $04700008 Current Load
constant RI_SELECT($0C)       // $0470000C Select
constant RI_REFRESH($10)      // $04700010 Refresh
constant RI_LATENCY($14)      // $04700014 Latency
constant RI_RERROR($18)       // $04700018 Read Error
constant RI_WERROR($1C)       // $0470001C Write Error
