constant AI_BASE($A450)    // $04500000..$04500017 Audio Interface (AI) Base Register
constant AI_DRAM_ADDR($00) // $04500000..$04500003 AI: DRAM Address Register
constant AI_LEN($04)       // $04500004..$04500007 AI: Length Register
constant AI_CONTROL($08)   // $04500008..$0450000B AI: Control Register
constant AI_STATUS($0C)    // $0450000C..$0450000F AI: Status Register
constant AI_DACRATE($10)   // $04500010..$04500013 AI: DAC Sample Period Register
constant AI_BITRATE($14)   // $04500014..$04500017 AI: Bit Rate Register
