constant RI_BASE($A470)       // $04700000..$0470001F RDRAM Interface (RI) Base Register
constant RI_MODE($00)         // $04700000..$04700003 RI: Mode Register
constant RI_CONFIG($04)       // $04700004..$04700007 RI: Config Register
constant RI_CURRENT_LOAD($08) // $04700008..$0470000B RI: Current Load Register
constant RI_SELECT($0C)       // $0470000C..$0470000F RI: Select Register
constant RI_REFRESH($10)      // $04700010..$04700013 RI: Refresh Register
constant RI_LATENCY($14)      // $04700014..$04700017 RI: Latency Register
constant RI_RERROR($18)       // $04700018..$0470001B RI: Read Error Register
constant RI_WERROR($1C)       // $0470001C..$0470001F RI: Write Error Register
